# Numpy

In [1]:
import numpy as np

## Creating Arrays

In [2]:
my_list = [0,1,2,3,4]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([0, 1, 2, 3, 4])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Operations

In [9]:
arr = np.random.randint(0,100,10)

In [10]:
arr

array([35, 83, 33, 58, 87, 96, 48, 41, 44,  4])

In [11]:
arr.max()

np.int64(96)

In [12]:
arr.min()

np.int64(4)

In [13]:
arr.mean()

np.float64(52.9)

In [14]:
arr.argmin()

np.int64(9)

In [15]:
arr.argmax()

np.int64(5)

In [16]:
arr.reshape(2,5)

array([[35, 83, 33, 58, 87],
       [96, 48, 41, 44,  4]])

## Indexing

In [17]:
# np.arange(0,100)

In [18]:
mat = np.arange(0,100).reshape(10,10)

In [19]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
mat[ 3:6 , 0:4 ]

array([[30, 31, 32, 33],
       [40, 41, 42, 43],
       [50, 51, 52, 53]])

In [21]:
row = 0
col = 1

In [22]:
mat[row,col]

np.int64(1)

In [23]:
# mat[ : , : ]

In [24]:
# With Slices
mat[:,col]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [25]:
mat[row,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

# Great Job!